#!/usr/bin/env python3
"""Generate weekly governance compliance report.

Usage:
  python generate_weekly_report.py --input report.json --output weekly.md
"""

import json
import sys
from datetime import datetime
from pathlib import Path


def calculate_health_score(compliant: int, total: int, violations: int = 0) -> int:
    """Calculate fleet governance health score (0-100).

    Score based on:
    - Compliance rate (60% weight)
    - Violations count (40% weight)
    """
    compliance_score = (compliant / total) * 100 if total > 0 else 0
    violation_penalty = min(violations * 5, 40)  # Max 40 point penalty
    return int(max(0, compliance_score * 0.6 + (100 - violation_penalty) * 0.4))


def generate_report(input_file: Path, output_file: Path) -> None:
    """Generate weekly governance report."""
    with open(input_file) as f:
        data = json.load(f)

    compliant_count = sum(1 for r in data if r['valid'])
    total_count = len(data)
    health_score = calculate_health_score(compliant_count, total_count)

    report = f"""# Fleet Governance Weekly Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
**Period:** Last 7 days

## 📊 Health Score

**Score:** {health_score}/100 {'✅' if health_score >= 90 else '⚠️' if health_score >= 70 else '❌'}

Trend analysis will track week-over-week improvements.

## ✅ Compliance Status

- **Compliant Repos:** {compliant_count}/{total_count}
- **Compliance Rate:** {(compliant_count/total_count*100):.1f}%
- **Schema Version:** 1.0

### Compliant Repos ({compliant_count})
"""

    compliant_repos = sorted([r['repo_name'] for r in data if r['valid']])
    for repo in compliant_repos:
        report += f"- ✅ {repo}\n"

    non_compliant = [r for r in data if not r['valid']]
    if non_compliant:
        report += f"\n### Non-Compliant Repos ({len(non_compliant)})\n"
        for repo in non_compliant:
            report += f"- ❌ {repo['repo_name']}\n"
            for error in repo.get('errors', []):
                report += f"  - {error}\n"

    report += """
## 🎯 Action Items

"""
    if health_score == 100:
        report += "- ✅ All repos compliant—no action needed\n"
    else:
        report += "- ⚠️ Review non-compliant repos above\n"
        report += "- 📋 Run: `cd fleet-coordination && just check-governance-repo <repo>`\n"

    report += """
## 📚 Resources

- [Compliance Checker](fleet-coordination/.fleet/governance-compliance-checker.md)
- [Schema v1.0](fleet-base/.fleet/governance-schema-v1.md)
- [Status Dashboard](fleet-coordination/GOVERNANCE_STATUS.md)

---

*Generated by `generate_weekly_report.py`*
"""

    with open(output_file, 'w') as f:
        f.write(report)

    print(f"✅ Report generated: {output_file}")
    print(f"   Health Score: {health_score}/100")
    print(f"   Compliance: {compliant_count}/{total_count}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True, help="Input JSON report")
    parser.add_argument("--output", type=Path, required=True, help="Output markdown file")
    args = parser.parse_args()

    generate_report(args.input, args.output)
